id: com.PrivatusAI.PrivatusAI
runtime: org.freedesktop.Platform
runtime-version: '23.08'
sdk: org.freedesktop.Sdk
command: privatusai

finish-args:
  - --share=ipc
  - --socket=x11
  - --socket=wayland
  - --share=network
  - --socket=pulseaudio
  - --device=all

modules:
  - name: privatusai
    buildsystem: simple
    sources:
      - type: git
        url: https://github.com/MokaNiax/PrivatusAI.git
        tag: v1.0.0
      - type: dir
        path: flatpak_file
    build-commands:
      - flutter build linux --release --project-dir=privatusai_app
      
      - mkdir -p /app/privatusai_bundle
      
      - cp -a privatusai_app/build/linux/x64/release/bundle/. /app/privatusai_bundle/
      
      - install -Dm755 /app/privatusai_bundle/privatusai_app /app/bin/com.PrivatusAI.PrivatusAI
      - install -Dm644 flatpak_files/com.PrivatusAI.PrivatusAI.desktop /app/share/applications/com.PrivatusAI.PrivatusAI.desktop
      - install -Dm644 flatpak_files/icon.png /app/share/icons/hicolor/scalable/apps/com.PrivatusAI.PrivatusAI.png
